export const subjects = [
  {
    id: "math",
    label: "数学",
    icon: "∑",
    minutes: 25,
    color: "#14B8A6",
    station: "计算与思路站",
  },
  {
    id: "english",
    label: "英语",
    icon: "Aa",
    minutes: 20,
    color: "#8B5CF6",
    station: "词句表达站",
  },
  {
    id: "chinese",
    label: "语文",
    icon: "文",
    minutes: 20,
    color: "#F59E0B",
    station: "阅读表达站",
  },
  {
    id: "preview",
    label: "初一预习",
    icon: "7",
    minutes: 10,
    color: "#10B981",
    station: "新学期预备站",
  },
];

export const questionBank = [
  {
    id: "math-writing-1",
    subject: "math",
    type: "choice",
    knowledge: "数学卷面规范",
    prompt: "做百分数、折扣类计算时，哪种写法最能减少看错和算错？",
    options: [
      "一个数字占一格，等号上下尽量对齐",
      "把草稿和答案都挤在同一行",
      "为了快一点，省略小数点和单位",
      "想到哪里写到哪里，不需要留空",
    ],
    answer: "一个数字占一格，等号上下尽量对齐",
    explanation: "六年级应用题里，数字、等号、小数点看清楚很关键。用方格和对齐可以让步骤更容易自查。",
    coachTip: "先把卷面写清楚，很多“粗心错”会自动减少。",
  },
  {
    id: "math-percent-1",
    subject: "math",
    type: "choice",
    knowledge: "分数百分数",
    prompt: "把 3/8 化成百分数，正确的是哪一个？",
    options: ["37.5%", "38%", "35%", "0.375%"],
    answer: "37.5%",
    explanation: "3 ÷ 8 = 0.375，再乘 100% 就是 37.5%。",
    coachTip: "分数转百分数时，先变小数，再看百分号。",
  },
  {
    id: "math-equation-1",
    subject: "math",
    type: "input",
    knowledge: "简易方程",
    prompt: "解方程：3x + 5 = 20，x = ?",
    answer: "5",
    acceptableAnswers: ["5", "x=5", "x = 5"],
    explanation: "先两边同时减 5，得到 3x = 15，再除以 3，x = 5。",
    coachTip: "方程题要每一步都对等，别在心算里跳太快。",
  },
  {
    id: "math-word-1",
    subject: "math",
    type: "choice",
    knowledge: "应用题审题",
    prompt: "一本书 240 页，小林已经读了 3/5，还剩多少页？",
    options: ["96 页", "144 页", "120 页", "80 页"],
    answer: "96 页",
    explanation: "已读 3/5，剩下 2/5。240 × 2/5 = 96。",
    coachTip: "看到“还剩”，先把剩下的比例找出来。",
  },
  {
    id: "english-tense-1",
    subject: "english",
    type: "input",
    knowledge: "一般现在时",
    prompt: "用所给词的正确形式填空：He ___ to school by bus every day. (go)",
    answer: "goes",
    acceptableAnswers: ["goes"],
    explanation: "主语 He 是第三人称单数，一般现在时动词 go 要变 goes。",
    coachTip: "看到 he/she/it 和 every day，先提醒自己动词三单。",
  },
  {
    id: "english-words-1",
    subject: "english",
    type: "choice",
    knowledge: "高频词汇",
    prompt: "Which word means “重要的”？",
    options: ["important", "different", "difficult", "interesting"],
    answer: "important",
    explanation: "important 表示“重要的”。different 是“不同的”，difficult 是“困难的”。",
    coachTip: "容易混的词可以放在一句自己的例句里记。",
  },
  {
    id: "english-sentence-1",
    subject: "english",
    type: "choice",
    knowledge: "基础句子结构",
    prompt: "下面哪一句语序正确？",
    options: ["I like reading books.", "I reading like books.", "Like I reading books.", "Books I like reading."],
    answer: "I like reading books.",
    explanation: "英语基本语序通常是主语 + 谓语 + 宾语。",
    coachTip: "写句子时先找主语，再找动作。",
  },
  {
    id: "chinese-reading-1",
    subject: "chinese",
    type: "choice",
    knowledge: "概括表达",
    prompt: "概括文章段落大意时，最重要的是先找什么？",
    options: ["中心句或主要事件", "生僻字", "作者年龄", "标点数量"],
    answer: "中心句或主要事件",
    explanation: "段落大意要抓主要内容，不被细节带跑。",
    coachTip: "先问自己：这一段主要讲了谁，做了什么，结果怎样。",
  },
  {
    id: "chinese-poem-1",
    subject: "chinese",
    type: "input",
    knowledge: "古诗文积累",
    prompt: "补全诗句：不识庐山真面目，___。",
    answer: "只缘身在此山中",
    acceptableAnswers: ["只缘身在此山中"],
    explanation: "这句出自苏轼《题西林壁》，常考理解和默写。",
    coachTip: "古诗默写错字，最好用一句话理解画面再记。",
  },
  {
    id: "chinese-writing-1",
    subject: "chinese",
    type: "choice",
    knowledge: "作文结构",
    prompt: "写一件难忘的事，开头最适合先交代什么？",
    options: ["事情发生的时间、地点和人物", "大量无关景物", "结尾升华", "所有人物外貌"],
    answer: "事情发生的时间、地点和人物",
    explanation: "记事作文开头要让读者先进入场景。",
    coachTip: "写事先搭场景，再写冲突和变化。",
  },
  {
    id: "preview-number-1",
    subject: "preview",
    type: "choice",
    knowledge: "有理数",
    prompt: "初一会学有理数。下面哪个数是负数？",
    options: ["-3", "0", "2.5", "1/2"],
    answer: "-3",
    explanation: "小于 0 的数是负数，-3 在 0 的左边。",
    coachTip: "初中数学会更重视数轴和符号意识。",
  },
  {
    id: "preview-expression-1",
    subject: "preview",
    type: "input",
    knowledge: "代数式",
    prompt: "用代数式表示：一个数 x 的 2 倍再加 3。",
    answer: "2x+3",
    acceptableAnswers: ["2x+3", "2*x+3", "2x + 3", "2 * x + 3"],
    explanation: "x 的 2 倍是 2x，再加 3 就是 2x + 3。",
    coachTip: "代数式就是把文字关系翻译成数学符号。",
  },
];

export const coachCards = [
  {
    id: "math-handwriting",
    title: "数学卷面 5 分钟微训练",
    tag: "Claude 导入",
    tone: "skill",
    points: [
      "每天只练 0-9、=、%、小数点，重点区分 3/5、7/9。",
      "草稿区和正式答案分开，正式区只保留关键步骤。",
      "做题时一个数字占一格，等号尽量排成一列。",
    ],
  },
  {
    id: "hobby-boundary",
    title: "爱好不禁掉，但要有边界",
    tag: "家庭规则",
    tone: "habit",
    points: [
      "不要把矛头对准孩子的兴趣，核心问题是时间和优先级。",
      "学习任务完成后，爱好时间才稳定兑现。",
      "规则写具体：什么时候学、学到什么程度、周末可用多久。",
    ],
  },
  {
    id: "semantic-tree",
    title: "自学先搭树干，再挂树叶",
    tag: "学习方法",
    tone: "method",
    points: [
      "先问：这个知识点最底层的概念是什么？",
      "再做：用 2-3 道题确认主干是否站稳。",
      "最后补：错题、技巧和细节都挂到对应主干上。",
    ],
  },
];

export function buildDefaultSession(dateIso) {
  return {
    dateIso,
    energy: "",
    currentSubject: "math",
    answers: {},
    knowledgeStatus: {},
    reflection: "",
    parentBrief: "",
  };
}
